In [1]:
# Number and String

import numpy as np

In [2]:
print(type(2))
print(type(3.33))
print(type('uttam'))

<class 'int'>
<class 'float'>
<class 'str'>


In [3]:
print(type(range(1,10)))

<class 'range'>


In [4]:
for i in range(10.11):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [6]:
name = "Uttam"

In [10]:
# + use for concatenation and * use for concatenate this multipule time
print('Hello ' + name)
print(3 * name)

Hello Uttam
UttamUttamUttam


In [9]:
%whos

Variable   Type      Data/Info
------------------------------
i          int       9
name       str       Uttam
np         module    <module 'numpy' from 'D:\<...>ges\\numpy\\__init__.py'>


In [15]:
# int() , float(), 

s1 = '4'
s2 = '4.3'
n1 = 5
n2 = 5.5

print(int(s1))
print(int(float(s2)))

print(float(s1))
print(float(s2))

print(str(n1))
print(str(n2) + str(555))

4
4
4.0
4.3
5
5.5555


# List and Numpy Array

In [16]:
alist = [1,2,3,4,5,6,7]
print(type(alist))
list_list = [1,2,['3','8','9'],4,5,6,7]
print(list_list)

<class 'list'>
[1, 2, ['3', '8', '9'], 4, 5, 6, 7]


In [19]:
slist = ['1', '2', '3', '4']
print(alist + slist)
print(alist * 3)

[1, 2, 3, 4, 5, 6, 7, '1', '2', '3', '4']
[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]


In [21]:
np_alist = np.array(alist)
print(type(np_alist))
print(alist)
print(np_alist)

<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7]
[1 2 3 4 5 6 7]


In [22]:
print(np_alist)
print(np_alist * 4)

[1 2 3 4 5 6 7]
[ 4  8 12 16 20 24 28]


In [23]:
print(np_alist)
print(np_alist + 4)

[1 2 3 4 5 6 7]
[ 5  6  7  8  9 10 11]


## for ind, item in enumerate(list_list):

In [25]:
for ind, item in enumerate(list_list):
    print(f'index {ind} and value {item} in list {list_list}')

index 0 and value 1 in list [1, 2, ['3', '8', '9'], 4, 5, 6, 7]
index 1 and value 2 in list [1, 2, ['3', '8', '9'], 4, 5, 6, 7]
index 2 and value ['3', '8', '9'] in list [1, 2, ['3', '8', '9'], 4, 5, 6, 7]
index 3 and value 4 in list [1, 2, ['3', '8', '9'], 4, 5, 6, 7]
index 4 and value 5 in list [1, 2, ['3', '8', '9'], 4, 5, 6, 7]
index 5 and value 6 in list [1, 2, ['3', '8', '9'], 4, 5, 6, 7]
index 6 and value 7 in list [1, 2, ['3', '8', '9'], 4, 5, 6, 7]


In [31]:
import sympy as sym
import handcalcs.render

In [32]:
x = sym.symbols('x')
y = sym.symbols('y')

# 2x+4 = 9
expr = 2 * x + 4 -9

solution = sym.solve(expr)
print(solution)

[5/2]


In [38]:
expr = x/4 + y/6 + x**4 + 5*y
solution = sym.solve(expr, x)
print(solution)

# solution = sym.solve(expr, y)
# print(solution)

[Piecewise((-2**(1/3)*sqrt(-(-1)**(1/3))/4 + sqrt((-1)**(1/3)*2**(2/3)/4 + 2**(2/3)/(2*sqrt(-(-1)**(1/3))))/2, Eq(y, 0)), (-sqrt(31*y/(9*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3)) + 2*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3))/2 + sqrt(-31*y/(9*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3)) - 2*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3) + 1/(2*sqrt(31*y/(9*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3)) + 2*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3))))/2, True)), Piecewise((2**(1/3)*sqrt(-(-1)**(1/3))/4 - sqrt(-2**(2/3)/(2*sqrt(-(-1)**(1/3))) + (-1)**(1/3)*2**(2/3)/4)/2, Eq(y, 0)), (sqrt(31*y/(9*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3)) + 2*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3))/2 - sqrt(-31*y/(9*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3)) - 2*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3) - 1/(2*sqrt(31*y/(9*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3)) + 2*(sqrt(1/65536 - 29791*y**3/5832) + 1/256)**(1/3))))/2, True)), Piec

In [39]:
%%render
solution

<IPython.core.display.Latex object>

In [44]:
solution = sym.solve(expr, y)
print(solution)

[3*x*(-4*x**3 - 1)/62]


In [45]:
%%render
solution

<IPython.core.display.Latex object>

In [47]:
solution = sym.solve(expr)
print(solution)

[{y: 3*x*(-4*x**3 - 1)/62}]


In [50]:
from IPython.display import display, Math

In [55]:
q = sym.symbols('q')

eq = 3*q + 4/q + 3 -(5*q + 1/q +1)
display(Math(sym.latex(sym.cancel(eq))))
display(Math(sym.latex(eq.simplify())))

display(Math("q = " + sym.latex(sym.solve(eq))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [62]:
eq2 = expr.subs(y, 10)

In [63]:
expr.subs(y, 10).evalf()

x**4 + 0.25*x + 51.6666666666667

In [68]:
solution = sym.solve(eq2)
print(solution)

[-sqrt(310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)) + 2*(1/256 + sqrt(244047871271)*I/6912)**(1/3))/2 - sqrt(-2*(1/256 + sqrt(244047871271)*I/6912)**(1/3) + 1/(2*sqrt(310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)) + 2*(1/256 + sqrt(244047871271)*I/6912)**(1/3))) - 310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)))/2, sqrt(310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)) + 2*(1/256 + sqrt(244047871271)*I/6912)**(1/3))/2 - sqrt(-2*(1/256 + sqrt(244047871271)*I/6912)**(1/3) - 1/(2*sqrt(310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)) + 2*(1/256 + sqrt(244047871271)*I/6912)**(1/3))) - 310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)))/2, sqrt(-2*(1/256 + sqrt(244047871271)*I/6912)**(1/3) - 1/(2*sqrt(310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)) + 2*(1/256 + sqrt(244047871271)*I/6912)**(1/3))) - 310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)))/2 + sqrt(310/(9*(1/256 + sqrt(244047871271)*I/6912)**(1/3)) + 2*(1/256 + sqrt(244047871271)*I/6912)**(1/3))/2, sqrt(-2*(1/256